name: Update TikTok Posts

on:
  schedule:
    # Schedule to run the workflow every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install TikTok Scraper
        run: npm install git+https://github.com/fadytaher/tiktok-scraper.git


      - name: Fetch TikTok Posts
        id: fetch_tiktok_posts
        run: npx tiktok-scraper user harunnryd -n 300 -t json --session sid_tt=b10309d835ce661182866102e822df91 --filename posts

      - name: Read TikTok posts template from README.md
        id: read_template
        run: |
          TEMPLATE_CONTENT=$(sed -n '/<!-- TIKTOK-POST-LIST:START -->/,/<!-- TIKTOK-POST-LIST:END -->/p' README.md)
          echo "::set-output name=template::$TEMPLATE_CONTENT"

      - name: Generate new TikTok posts content
        id: generate_tiktok_posts_content
        run: |
          cat posts.json | jq -r '.[] | "- [" + .text + "](" + .videoUrl + ")"' > tiktok_posts.md
          echo "::set-output name=content::$(cat tiktok_posts.md)"

      - name: Merge template and new TikTok posts content
        id: merge_template
        run: |
          template="${{ steps.read_template.outputs.template }}"
          content="${{ steps.generate_tiktok_posts_content.outputs.content }}"
          new_content="$template\n$content"
          echo "::set-output name=content::$new_content"

      - name: Compare current and new content
        id: compare_content
        run: |
          current_content=$(cat README.md | sed -n '/<!-- TIKTOK-POST-LIST:START -->/,/<!-- TIKTOK-POST-LIST:END -->/p')
          new_content="${{ steps.merge_template.outputs.content }}"
          if [ "$current_content" = "$new_content" ]; then
            echo "No new TikTok content to update."
            exit 0
          fi

      - name: Update TikTok section in README.md
        if: steps.compare_content.outputs.code == '0'
        run: |
          new_content="${{ steps.merge_template.outputs.content }}"
          sed -i '/<!-- TIKTOK-POST-LIST:START -->/,/<!-- TIKTOK-POST-LIST:END -->/c\'"$new_content"'' README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update TikTok posts"
          git push