name: Update TikTok Posts

on:
  schedule:
    # Schedule to run the workflow every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install TikTok Scraper
        run: npm install git+https://github.com/fadytaher/tiktok-scraper.git

      - name: Fetch TikTok Posts
        run: npx tiktok-scraper user harunnryd -n 300 -t json --session sid_tt=b10309d835ce661182866102e822df91 --filename posts

      - name: Wait for file to be created
        run: sleep 10

      - name: Generate TikTok Posts List
        id: generate_tiktok_posts
        run: |
          cat posts.json | jq -r '.[] | "- [" + .text + "](" + .videoUrl + ")"' > tiktok_posts.md

      - name: Update README.md
        run: |
          # Replace TikTok posts content
          awk -v start="<!-- TIKTOK-POST-LIST:START -->" -v end="<!-- TIKTOK-POST-LIST:END -->" \
              'NR==FNR { a[i++]=$0; next } /<!-- TIKTOK-POST-LIST:START -->/ { f=1; print; system("cat tiktok_posts.md"); next } /<!-- TIKTOK-POST-LIST:END -->/ { f=0 } !f { print } END { if (!f) for (j=0; j<i; j++) print a[j] }' \
              README.md README.md > README.new.md

          # Overwrite the original README.md with the updated content
          mv README.new.md README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update TikTok posts"
          git push