name: Update TikTok Posts

on:
  schedule:
    # Schedule to run the workflow every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install TikTok Scraper
        run: npm install git+https://github.com/fadytaher/tiktok-scraper.git


      - name: Fetch TikTok Posts
        run: npx tiktok-scraper user harunnryd -n 300 -t json --session sid_tt=b10309d835ce661182866102e822df91 --filename posts

      - name: Remove unnecessary files
        run: |
          rm -rf node_modules/
          rm package-lock.json
          rm posts.json

      - name: Update README.md Template Section
        run: |
          # Extract the content between the template markers from the current README.md
          TEMPLATE_CONTENT=$(awk '/<!-- TIKTOK-POST-LIST:START -->/,/<!-- TIKTOK-POST-LIST:END -->/ {print}' README.md)

          # Replace newline with the string "<br>" in new_posts
          ESCAPED_POSTS=$(cat posts.json | jq -r '.[] | "- [" + .text + "](" + .videoUrl + ")"' | awk '{printf "%s\\n", $0}')

          # Update the README.md
          awk -v new_posts="$ESCAPED_POSTS" '
            /<!-- TIKTOK-POST-LIST:START -->/ {
              p=1;
              print;
              print new_posts;
              next;
            }
            /<!-- TIKTOK-POST-LIST:END -->/ {
              p=0;
              print;
              next;
            }
            !p' README.md > README_new.md

          # Replace the original README with the updated one
          mv README_new.md README.md

      - name: Stage changes
        run: git add README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update TikTok posts"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}