name: Update TikTok Posts

on:
  schedule:
    # Schedule to run the workflow every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install TikTok Scraper
        run: npm install git+https://github.com/fadytaher/tiktok-scraper.git

      - name: Fetch TikTok Posts
        run: npx tiktok-scraper user harunnryd -n 300 -t json --session sid_tt=b10309d835ce661182866102e822df91 --filename posts

      - name: Wait for file to be created
        run: sleep 10

      - name: Update README.md Template Section
        run: |
          # Extract the content between the template markers from the current README.md
          TEMPLATE_CONTENT=$(sed -n '/<!-- TIKTOK-POST-LIST:START -->/,/<!-- TIKTOK-POST-LIST:END -->/p' README.md)

          # Create a temporary file with the fetched TikTok posts
          echo "<!-- TIKTOK-POST-LIST:START -->" > temp.md
          cat posts.json | jq -r '.[] | "- [" + .text + "](" + .videoUrl + ")"' >> temp.md
          echo "<!-- TIKTOK-POST-LIST:END -->" >> temp.md

          # Replace the content between the template markers with the fetched TikTok posts
          sed -i '/<!-- TIKTOK-POST-LIST:START -->/,/<!-- TIKTOK-POST-LIST:END -->/d' README.md
          cat temp.md >> README.md
          rm temp.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update TikTok posts"
          git push
