name: Update TikTok Posts

on:
  schedule:
    # Schedule to run the workflow every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install TikTok Scraper
        run: npm install tiktok-scraper

      - name: Fetch TikTok Posts
        run: |
          TIKTOK_DATA=$(npx tiktok-scraper user harunnryd -n 10 --session sid_tt=b10309d835ce661182866102e822df91)
          echo "TIKTOK_DATA=$TIKTOK_DATA" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          # Read existing README.md content
          readme_content=$(cat README.md)
  
          # Check if the template markers exist in README.md
          if [[ $readme_content == *'<!-- TIKTOK-POST-LIST:START -->'* ]]; then
            # Extract the content between the template markers
            content=$(echo "$readme_content" | awk '/<!-- TIKTOK-POST-LIST:START -->/{flag=1;next}/<!-- TIKTOK-POST-LIST:END -->/{flag=0}flag')
  
            # Remove the existing content between the template markers
            new_readme_content=$(echo "$readme_content" | sed '/<!-- TIKTOK-POST-LIST:START -->/,/<!-- TIKTOK-POST-LIST:END -->/d')
          else
            # If the template markers do not exist, set content to an empty string
            content=""
            new_readme_content="$readme_content"
          fi
  
          # Add new content between the template markers
          new_readme_content+="<!-- TIKTOK-POST-LIST:START -->"$'\n'
          IFS=$'\n'
          for line in $TIKTOK_DATA; do
            text=$(echo "$line" | jq -r '.text')
            videoUrl=$(echo "$line" | jq -r '.videoUrl')
            new_readme_content+="- [$text]($videoUrl)"$'\n'
          done
          unset IFS
          new_readme_content+=$'\n'"<!-- TIKTOK-POST-LIST:END -->"
  
          # Update the README.md file
          echo "$new_readme_content" > README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update TikTok posts"
          git push
