name: Update TikTok Posts

on:
  schedule:
    # Schedule to run the workflow every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install TikTok Scraper
        run: npm install tiktok-scraper

      - name: Fetch TikTok Posts
        run: npx tiktok-scraper user harunnryd -n 300 -t json --session sid_tt=b10309d835ce661182866102e822df91 --filename posts.json

      - name: Update README.md
        run: |
          # Check if the template exists in README.md
          if grep -q "<!-- TIKTOK-POST-LIST:START -->" README.md; then
            # Remove the existing content between the template markers
            sed -i '/<!-- TIKTOK-POST-LIST:START -->/,/<!-- TIKTOK-POST-LIST:END -->/d' README.md
          fi
          # Add new content between the template markers and store it in a temporary file
          echo "<!-- TIKTOK-POST-LIST:START -->" > temp.md
          cat posts.json | jq -r '.collector[] | "- [" + .text + "](" + .videoUrl + ")"' >> temp.md
          echo "<!-- TIKTOK-POST-LIST:END -->" >> temp.md
          # Replace the original README.md with the temporary file
          mv temp.md README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update TikTok posts"
          git push
